import React, { Suspense } from 'react'
import Todo from '../components/Todo';

export const metadata = {
    title: "postssss",
    description: "Generated by upskilling",
};

export default async function postspage() {

    const response = await fetch('https://jsonplaceholder.typicode.com/posts', { next: { novalidate: 120 } });
    const posts = await response.json()


    return (
        //         <div className="grid grid-cols-1 gap-4 lg:grid-cols-4 lg:gap-8">
        //   <div className="h-32 rounded-lg bg-gray-200"></div>
        //   <div className="h-32 rounded-lg bg-gray-200"></div>
        //   <div className="h-32 rounded-lg bg-gray-200"></div>
        //   <div className="h-32 rounded-lg bg-gray-200"></div>
        // </div>
        <>
            {/* <Todo /> */}
            <h1 className='text-center bg-purple-600 p-5'>Upskilling Advanced Round2</h1>
            <Suspense fallback={<h1>loadingggg.....</h1>}>
                <div className="overflow-x-auto">
                    <table className="min-w-full divide-y-2 divide-gray-200 bg-white text-sm">
                        <thead className="ltr:text-left rtl:text-right">
                            <tr>
                                <th className="whitespace-nowrap px-4 py-2 font-medium text-gray-900">Post id</th>
                                <th className="whitespace-nowrap px-4 py-2 font-medium text-gray-900">Post title</th>
                                <th className="whitespace-nowrap px-4 py-2 font-medium text-gray-900">Post description</th>
                            </tr>
                        </thead>

                        <tbody className="divide-y divide-gray-200">
                            {posts.map((post) => <tr key={post.id} className="odd:bg-gray-50">
                                <td className="whitespace-nowrap px-4 py-2 font-medium text-gray-900">{post.id}</td>
                                <td className="whitespace-nowrap px-4 py-2 text-gray-700">{post.title}</td>
                                <td className="whitespace-nowrap px-4 py-2 text-gray-700">{post.body}</td>
                            </tr>)}

                        </tbody>
                    </table>
                </div>
            </Suspense>
        </>
        // <ul>
        //     {posts.map((post) => <li>{post.title}</li>)}
        // </ul>
    )
}
